plugins {
    id "com.android.application"
    id "org.jetbrains.kotlin.android" version "1.9.0"
}

android {
    namespace "com.AntoineCFR.trackit"
    compileSdk 34

    lint {
        disable 'InvalidPackage'
    }

    defaultConfig {
        applicationId "com.AntoineCFR.trackit"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            keyAlias System.getenv('ANDROID_KEY_ALIAS') ?: 'trackit'
            keyPassword System.getenv('ANDROID_KEY_PASSWORD') ?: 'changeit'
            storeFile file(System.getenv('ANDROID_STORE_FILE') ?: 'trackit.keystore')
            storePassword System.getenv('ANDROID_STORE_PASSWORD') ?: 'changeit'
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    buildFeatures {
        viewBinding true
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation platform('com.google.firebase:firebase-bom:32.7.0')
    implementation 'com.google.firebase:firebase-analytics-ktx'
    implementation 'com.google.firebase:firebase-auth-ktx'
    implementation 'com.google.firebase:firebase-firestore-ktx'
    implementation 'com.google.android.gms:play-services-auth:20.7.0'
    implementation 'androidx.lifecycle:lifecycle-process:2.6.2'
}

apply plugin: 'com.google.gms.google-services'
